services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - internal
  server:
    image: chromadb/chroma
    volumes:
      - chroma_data:/data
    ports:
      - "8000:8000"
    networks:
      - internal
    environment:
      - CHROMA_OPEN_TELEMETRY__SERVICE_NAME=chroma
      - OTEL_METRICS_EXPORTER=none
    depends_on:
      - zipkin

networks:
  internal:

volumes:
  chroma_data:
